# Social media links

# GitHub
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/briansuarezsantiago"

[social.params]
icon = "brand-github"

# LinkedIn
[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/briansuarezsantiago"

[social.params]
icon = "brand-linkedin"

# Email
[[social]]
identifier = "email"
name = "Email"
url = "mailto:bbriansuarezsantiago@protonmail.com"

[social.params]
icon = "brand-email"

# RSS Feed
[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "rss"
