baseURL="https://brianintech.com"
languageCode="en-us"
title="Brian Su√°rez Santiago"
theme="hugo-theme-stack"
ignoreLogs = ['warning-goldmark-raw-html']
titleCaseStyle = 'none'
uglyURLs = true
googleAnalytics= 'G-X0632M0DP7'
